#
#  This file is read when going to multi-user and its contents piped thru
#  ``sysctl'' to adjust kernel values.  ``man 5 sysctl.conf'' for details.
#

# Uncomment this to prevent users from seeing information about processes that
# are being run under another UID.
#security.bsd.see_other_uids=0
vfs.zfs.min_auto_ashift=12
#
# https://blog.crashed.org/setting-up-freebsd-with-comcast-ipv6/
# > This allows the machine to be both a router and accept router advertisements at the same time.
net.inet6.ip6.rfc6204w3=1

# prevent flapping caused by Energy Efficient Ethernet (EEE) — most probable
# EEE is a common culprit with the igc driver and was adjusted in FreeBSD 15.
dev.igc0.eee_control=0
dev.igc1.eee_control=0
dev.igc2.eee_control=0
dev.igc3.eee_control=0
dev.igc4.eee_control=0
dev.igc5.eee_control=0
